<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "z3sqloverride"
 *
 * Auto generated by Extension Builder 2017-06-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Z3 SQL Override',
    'description' => 'Loads the additional SQL file ext_tables_override.sql on top of the current database scheme from ext_tables.sql.',
    'category' => 'be',
    'author' => 'Timo Poppinga',
    'author_email' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
